### ISSUE TITLE
TracedAutoFinishExecutionContext no longer compiles with opentracing-util 0.33.0

### ISSUE THREAD

**Issue by pjfanning** [opentracing-contrib/scala-concurrent#6]
AutoFinishScope is deprecated up to v0.32.0 and then removed in v0.33.0.

The deprecation warning suggests using ThreadLocalScope but that implementation seems very different.

**Comment by mdedetrich** [comment]
I think that scala-concurrent needs to be updated to 0.33.0. It seems that `AutoFinishScope` has been removed because in the new API for OpenTracing they removed the ability to auto finish scopes because it was too easy to misuse in the context of error handling.

**Comment by malafeev** [comment]
I'm feeling that 0.33.0 is not supported by tracers yet (e.g. latest jaeger on 0.32.0).
But for 0.33.0 upgrade I propose to add `AutoFinishScope`, `AutoFinishScopeManager` to this library from 0.31.0 using copy-paste.

**Comment by malafeev** [comment]
cc @carlosalberto

**Comment by pjfanning** [comment]
I've experimentally copied the AutoFinishScope and AutoFinishScopeManager in https://github.com/pjfanning/scala-concurrent/tree/autofinish-copy

**Comment by malafeev** [comment]
how about tests, do the pass?

**Comment by pjfanning** [comment]
the units tests pass in my autofinish-copy branch

**Comment by mdedetrich** [comment]
I would get feedback from one of the opentracing dev's about whether a `AutoFinishScopeManager` is misleading and should even exist since the equivalent `ThreadLocal` version was removed from OpenTracing for a reason.

**Comment by carlosalberto** [comment]
Hey hey, so my impression is that this could be kept (copying the `AutoFinish*` members here), and list it as experimental or something along those lines. 

In this regard, it would also be nice to try to prevent the users from directly using the `AutoFinishScopeManager` API (this would mean making a few methods package private, such as `AutoFinishScope.capture()`), in order to not break too much the design of OT 0.33 ;)

**Comment by pjfanning** [comment]
I have https://github.com/opentracing-contrib/scala-concurrent/pull/8 - I made the capture functions package private.

It would still need more changes to compile against OT 0.33 though.

**Comment by malafeev** [comment]
upgraded to 0.33.0
